

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: olympics-javabackend
  namespace: efedorenko
  labels:
    run: olympics-javabackend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: olympics-javabackend
    spec:
      containers:
      - image: ${{DOCKER_IMAGE}}:${{FD_PROJECT_VERSION}}
        imagePullPolicy: Always
        name: olympics-javabackend
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: wrelease
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: olympics-javabackend-svc
  namespace: efedorenko
spec:
  selector:
    run: olympics-javabackend
  ports:
    - port: 8088
      targetPort: 3000
  type: ClusterIP
