
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    run: "{{ .Values.deployment.name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: "{{ .Values.deployment.name }}"
    spec:
      containers:
      - image: "{{ .Values.image.name }}"
        env:
        - name: OLYMPICS_DB_URL
          value: "{{ .Values.jdbc.url }}"
        imagePullPolicy: Always
        name: olympics-fmw
        ports:
        - containerPort: 8080
          protocol: TCP
