apiVersion: v1
kind: Service
metadata:
  name: olympics-mw-svc
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    run: "{{ .Values.deployment.name }}"
  ports:
    - port: 8088
      targetPort: 8080
  type: ClusterIP
